# Generated by Django 4.0.5 on 2022-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户号')),
                ('name', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
                ('region', models.CharField(max_length=25, verbose_name='地址')),
                ('birthday', models.CharField(max_length=10, verbose_name='生日')),
                ('picture', models.CharField(max_length=20, verbose_name='图片路径')),
                ('gender', models.CharField(max_length=4, verbose_name='性别')),
            ],
        ),
    ]
