# Generated by Django 4.0.5 on 2022-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_servers', '0002_alter_user_id_alter_user_birthday_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(upload_to='img', verbose_name='图片路径'),
        ),
    ]
