# Generated by Django 4.0.5 on 2022-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='卡号')),
                ('flower_name', models.CharField(max_length=20)),
            ],
        ),
    ]
