# Generated by Django 4.0.5 on 2022-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('author', models.CharField(max_length=10, verbose_name='作者名字')),
                ('time', models.CharField(max_length=10, verbose_name='发布时间')),
                ('text', models.TextField(verbose_name='文章内容')),
                ('picture', models.CharField(max_length=20, verbose_name='头像路径')),
            ],
        ),
    ]
