# Generated by Django 4.0.5 on 2022-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=25, verbose_name='作者名字'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(max_length=40, verbose_name='头像路径'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.CharField(max_length=25, verbose_name='发布时间'),
        ),
    ]
