# Generated by Django 4.0.5 on 2022-06-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_servers', '0002_alter_article_author_alter_article_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
    ]
