# Generated by Django 4.0.5 on 2022-06-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_servers', '0003_remove_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.CharField(default=2, max_length=40, verbose_name='头像路径'),
            preserve_default=False,
        ),
    ]
