# Generated by Django 4.0.5 on 2022-06-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_servers', '0004_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(max_length=100, verbose_name='头像路径'),
        ),
    ]
